ClanSystem:
  Economy:
    Enabled: true
    Name: 'Coin(s)'
    #Priority list for economy systems
    #Available values: EXP, Essentials, Vault, GemsEconomy, PlayerPoints
    priority:
      - Essentials
      - Vault
      - EXP
  Database:
    #Available Values: MySQL, SQLite
    Type: MySQL
    #if you choose MySQL
    MySQL:
      Host: 'localhost:3306'
      Database: 'clansystem'
      Username: 'db-user'
      Password: 'password123'